version: '3'
services:
  proxy:
    # will build ./docker/proxy/Dockerfile
    build: ./docker/proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      internal:
        ipv4_address: 172.17.250.2
        ipv6_address: fd07:d1d9:0cae:62b2::2
    volumes:
      - ./caddy:/opt/caddy/
  website:
    build: ./docker/website
    networks:
      internal:
        ipv4_address: 172.17.250.3
        ipv6_address: fd07:d1d9:0cae:62b2::3

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: "172.17.250.0/24"
        - subnet: "fd07:d1d9:0cae:62b2::/64"