version: '3'
services:
  proxy:
    # will build ./docker/proxy/Dockerfile
    build: ./docker/proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      internal:
        ipv4_address: 10.245.233.34
        ipv6_address: "fd86:e070:5705:620a::34"
    volumes:
      - ./caddy:/opt/caddy/
  website:
    build: ./docker/website
    networks:
      internal:
        ipv4_address: 10.245.233.35
        ipv6_address: "fd86:e070:5705:620a::35"

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: "10.245.233.32/27"
        - subnet: "fd86:e070:5705:620a::/64"